### ISSUE TITLE
Unable to create a transaction via CIM

### ISSUE THREAD

**Issue by MattHall** [AuthorizeNet/sdk-ruby#21]
I have successfully created a customer profile via the CIM API using the gem, and I can call ```validate_payment_profile``` to check that I can charge the card associated with the profile:

```ruby
transaction.validate_payment_profile(u.cim_payment_profile_token, u.cim_profile_token).success?
=> true
```

Te problem I'm seeing is that attempting to create a transaction via ```create_transaction_auth_capture``` fails every time with 
> The element 'createCustomerProfileTransactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has incomplete content. List of possible elements expected: 'refId, transaction' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'."

Code used to send that attempt was:
```ruby
transaction.create_transaction_auth_capture(100.99, u.cim_profile_token, u.cim_payment_profile_token)
```
The XML being sent to the API is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<createCustomerProfileTransactionRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <merchantAuthentication>
    <name>69...Ba</name>
    <transactionKey>58W...du8sL</transactionKey>
  </merchantAuthentication>
</createCustomerProfileTransactionRequest>
```
Which does seem to be missing more or less all of the detail required to make a charge. Is there something obvious I'm not doing / doing wrong?

The only lead I have at the moment is that the ```CIM_CREATE_TRANSACTION``` fields are using the fields definition of ```CREATE_TRANSACTION_FIELDS```, which in turn only includes the following:

```ruby
CREATE_TRANSACTION_FIELDS = [
        REFID_FIELDS,
        {:transaction => [], :_conditional => :select_transaction_type_fields},
        {:extraOptions => :extra_options}
      ]
```

The ```TRANSACTION_FIELDS``` should be included with the call to ```select_transaction_type_fields```, but it seems like they are not.

**Comment by MattHall** [comment]
@arktseytlin I don't suppose you've managed to recreate this issue, have you?

**Comment by arktseytlin** [comment]
Sorry, we are indeed busy! Can you send me your sample code again (minus the credentials of course). I will try it on our end.

Date: Tue, 6 Jan 2015 05:39:10 -0800

**Comment by brianmc** [comment]
Hi @MattHall, 

while we're looking into this there is an alternative now to using createCustomerProfileTransactionRequest.   We've recently updated our standard createTransaction method to accept profiles and we would actually like to deprecate createCustomerProfileTransaction so that developers have one method for doing payments regardless of the payment data (e.g. cards, payment profiles, bank accounts, apple pay, etc).

Here's a code sample, I'll also update the readme based on your feedback:


  require 'rubygems'
  require 'authorizenet'

  include AuthorizeNet::API

  transaction = Transaction.new('API_LOGIN_ID', 'TRANSACTION_KEY', :gateway => :sandbox)
  request = CreateTransactionRequest.new
  request.transactionRequest = TransactionRequestType.new
  request.transactionRequest.amount = 39.55

  request.transactionRequest.profile = CustomerProfilePaymentType.new
  request.transactionRequest.profile.customerProfileId = "30967676"
  request.transactionRequest.profile.paymentProfile = PaymentProfile.new
  request.transactionRequest.profile.paymentProfile.paymentProfileId = "27987444"
  
  request.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction

  response = transaction.create_transaction(request)

  if response.messages.resultCode == MessageTypeEnum::Ok
    puts "Successfully made a purchase (authorization code: #{response.transactionResponse.authCode})"
  else
    raise "Failed to make purchase."
  end

**Comment by MattHall** [comment]
:+1: Excellent - thanks, @brianmc. 

Guess this can be closed in favour of depreciating createCustomerProfileTransaction

**Comment by bappelt** [comment]
I am seeing this issue as well. Any update on this? I don't think I can use the mentioned wok around since it uses methods that are not present in the released version of the gem.

**Comment by brianmc** [comment]
Released gem should have everything on Master:  https://rubygems.org/gems/authorizenet

Are you using 1.8.3?

Brian

**Comment by bappelt** [comment]
Oh, I am still getting 1.8.2 because the app I am working on is still on ruby 1.9.2. Let me try to get that upgraded.

**Comment by bappelt** [comment]
Thanks. I am able to create a transaction with the new method. But when a transaction fails, the only information I can find is "Error" in the response.messages.resultCode. Where do I find information about why a transaction failed with this method?

**Comment by brianmc** [comment]
Hi Byron, apologies for the delay in responding here.  You can get more info by drilling down into the transactionResponse.errors collection.  E.g.

````ruby
    response.messages.messages[0].text
    response.transactionResponse.errors.errors[0].errorCode
    response.transactionResponse.errors.errors[0].errorText
````
Full sample for createTransaction here:

https://github.com/AuthorizeNet/sample-code-ruby/blob/master/PaymentTransactions/charge-credit-card.rb
