### ISSUE TITLE
nomethoderror transactionResponse

### ISSUE THREAD

**Issue by sheetalank** [AuthorizeNet/sdk-ruby#46]
Hi,
I am using the authorizenet gem and I'm getting a 'nomethoderror transactionResponse'  on the response object that is returned when the api for createtransaction times out. According to the api documentation, for a timed out or retry, the transactionResponse xml should have avsresultcode as 'R'. But looks the authoriznet gem is not getting(?)/returning this info in the responsexml?

Here's the code:
response = transaction.create_transaction(request)
transaction_response = response.transactionResponse

and here's the error:
NoMethodError (undefined method `transactionResponse' for #<Errno::ETIMEDOUT:0x007f54a2c36ec0>):

How do I handle a response where the api has timed out? Right now it throws the above exception.

**Comment by srmisra** [comment]
@sheetalank Can you please provide all the steps you took to help me replicate the issue and have a better understanding of the problem?

**Comment by srmisra** [comment]
The 'nomethoderror transactionResponse' in this case is obtained as the code was not able to connect to the authorizenet API. Thus, the response of the request does not have a transaction object. This maybe due to poor internet connection, firewall issues etc. Please provide more details to solve this issue. 

On the other hand the avsresultcode 'R' denotes something else. The result code does not denote that the Authorize.net API is not responding to the user requests but it denotes that the Address Verification Service (AVS) is not responding to the requests from Authorize.net API. For AVS Authorize.net API contacts the bank for credit card address verification which if does not responds the avsresultcode 'R' is returned. For more details visit [How do I use the Address Verification Service (AVS)? What settings should I configure?](https://support.authorize.net/authkb/index?page=content&id=A649)

Suggesting to close this issue.

**Comment by brianmc** [comment]
Closing this as there has not been any further response.

**Comment by mike-burns** [comment]
For others who enjoy a good code spelunking: `NoMethodError` is what ROXML raises if given input with no `<` when using the Nokogiri parser.

```
[14] pry(main)> AuthorizeNet::API::CreateTransactionResponse.from_xml("foo")
NoMethodError: undefined method `root' for nil:NilClass
from /home/mike/vanda/ruthinium-web/vendor/gems/roxml/lib/roxml/xml/parsers/nokogiri.rb:52:in `default_namespace'
```
