### ISSUE TITLE
Partial Refund to Unsettled Transaction

### ISSUE THREAD

**Issue by jeffleeismyhero** [AuthorizeNet/sdk-ruby#65]
When attempting to issue a partial refund to a transaction that has not been settled, the entire transaction is voided. Is there a specific way to handle partial refunds prior to settlement? If not, is there a method to check whether or not a transaction has settled?

**Comment by brianmc** [comment]
Apologies for the (very) delayed response.   In credit card processing you cannot refund an unsettled transaction because there has been no movement of funds to move back.  The appropriate action at that time is to just void the transaction, in other words stop it being settled at all.

In the future we're considering use of hypermedia in the API so that API clients don't need to have awareness of that payments domain knowledge to know which action to perform.  For now you can get unsettled transactions with http://developer.authorize.net/api/reference/#transaction-reporting-get-unsettled-transaction-list  and settled txns with http://developer.authorize.net/api/reference/#transaction-reporting-get-transaction-list and you can always check the transactionStatus field of any transaction with http://developer.authorize.net/api/reference/#transaction-reporting-get-transaction-details

**Comment by jeffleeismyhero** [comment]
Thank you for your response, @brianmc.

I do hope that this is changed in the future. Delaying execution of refunds is problematic, error prone, and would be a very complex implementation -- there are many intricate details involved in that process.
